# train and save eam weight
base: configs/training_msa-v1/metafile.yml
task: molecular_function
num_classes: 7038
top_k: 40
netD: timm_tresnet_m
optim: AMSGrad
epochs: 140
stop_epoch: 100
lr: 0.0001
pct_start: 0.1
batch_size: 32
wandb: transformer-v2