base: configs/evaluating_msa-v1/metafile.yml
task: biological_process
num_classes: 21312
top_k: 40
netD: timm_tresnet_m
trained_model: ema-fmax-highest.pth
no_eval: false
prediction_save: ./data/target/pred_seqs/msa-v1-7-26/bpo/ema-fmax-highest.npy