in_channels: 32
out_channels_G: 32
mode: test
top_k: 40
max_len: 2000
dataloader_num_workers: 10
msa_embedding_dim: 32
msa_encoding_strategy: emb
msa_max_size: 10000
ngf: 64
netG: resnet_4blocks
no_antialias: false
no_antialias_up: false
ndf: 64
netD: resnet50
replace_stride_with_dilation: 
  - false
  - false
  - false
no_dropout: false
normG: instance
normD: batch
protein_interpros: null
use_ipr_head: false
no_ipr_input: true
ipr_embed_dims: 2048
init_type: xavier
init_gain: 0.02
gpu_ids: 
  - 0
batch_size: 8
torch_compile: false